export const GET_VIDEOGAMES = 'GET_VIDEOGAMES';
export const GET_VIDEOGAME_NAME = 'GET_VIDEOGAME_NAME';
export const GET_GENRES = 'GET_GENRES';
export const GET_PLATFORMS = 'GET_PLATFORMS';
export const FILTER_GENRE = 'FILTER_GENRE';
export const POST_VIDEOGAME = 'POST_VIDEOGAME';
export const ERROR = 'ERROR';
export const RESET_ERROR = 'RESET_ERROR';